/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ramesh.panels;

import static java.lang.System.out;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import ramesh.data.CommonDataStore;
import ramesh.librarySystem.Author;
import ramesh.librarySystem.Book;

/**
 *
 * @author Rkaran
 */
public class AddBook extends javax.swing.JPanel {

    //List <Author> author = new ArrayList();
    /**
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
        
        for(Author author: CommonDataStore.author){
            this.comboAuthor.addItem(author);
        }
        System.out.println("Author Size "+CommonDataStore.author.size());
        DefaultTableModel tablemodel = (DefaultTableModel)this.tableBookList.getModel();
        for(Book book : CommonDataStore.book)
            tablemodel.addRow(book.getVectorBook());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboAuthor = new javax.swing.JComboBox();
        btnAddAuthor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAuthor = new javax.swing.JList();
        btnRemoveAuthor = new javax.swing.JButton();
        btnSaveBook = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBookList = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        listShowAuthor = new javax.swing.JList();

        jLabel1.setText("ISBN ");

        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Author");

        comboAuthor.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                comboAuthorMouseWheelMoved(evt);
            }
        });
        comboAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboAuthorMouseClicked(evt);
            }
        });
        comboAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAuthorActionPerformed(evt);
            }
        });

        btnAddAuthor.setText("Add Author");
        btnAddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAuthorActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listAuthor);

        btnRemoveAuthor.setText("Remove Author");
        btnRemoveAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAuthorActionPerformed(evt);
            }
        });

        btnSaveBook.setText("Save Book");
        btnSaveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBookActionPerformed(evt);
            }
        });

        jLabel3.setText("Title");

        tableBookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "ISBN", "Copies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBookListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBookList);

        listShowAuthor.setBorder(javax.swing.BorderFactory.createTitledBorder("Author List"));
        jScrollPane3.setViewportView(listShowAuthor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboAuthor, 0, 307, Short.MAX_VALUE)
                            .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(txtISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoveAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSaveBook, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddAuthor, btnRemoveAuthor, btnSaveBook});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboAuthor, jScrollPane1, txtISBN, txtTitle});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnAddAuthor)
                        .addGap(30, 30, 30)
                        .addComponent(btnRemoveAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSaveBook)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane2, jScrollPane3});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddAuthor, btnRemoveAuthor, btnSaveBook});

    }// </editor-fold>//GEN-END:initComponents

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void btnAddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAuthorActionPerformed
        
        DefaultListModel<Author> listmodel = new DefaultListModel<>();
        ListModel<Author> listauthor = this.listAuthor.getModel();
        for(int i =0; i < listauthor.getSize(); i++ ){
                listmodel.addElement(listauthor.getElementAt(i));
        }
        listmodel.addElement(((Author)this.comboAuthor.getSelectedItem()));
        
        this.listAuthor.setModel(listmodel);
        
    }//GEN-LAST:event_btnAddAuthorActionPerformed

    private void btnSaveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBookActionPerformed
        // TODO add your handling code here:
        //List<Author> auth= new ArrayList();
        if(this.listAuthor.getModel().getSize()>0 && !this.txtISBN.getText().equals("") && !this.txtTitle.getText().equals(""))
        {            
            ListModel<Author> listmodel = this.listAuthor.getModel();
            
            Book newbook = new Book(this.txtTitle.getText(), this.txtISBN.getText());
            int count = 0;
            for (int i = 0; i < listmodel.getSize(); i++) {
                newbook.addAuthor(listmodel.getElementAt(i));
                count++;
            }
            CommonDataStore.book.add(newbook);
            DefaultTableModel tablemodel = (DefaultTableModel)this.tableBookList.getModel();
            tablemodel.addRow(newbook.getVectorBook());
            
            
            
            //System.out.println(count+ " author added to book "+newbook.getTitle());
            System.out.println("Table " + this.tableBookList.getRowCount());
        } 
        else
            JOptionPane.showMessageDialog(null, "Fill total requirments", "Incomplete Data", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnSaveBookActionPerformed

    private void btnRemoveAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAuthorActionPerformed
        Author auth = (Author)this.listAuthor.getSelectedValue();
        
        DefaultListModel<Author> listmodel = null;
        if (auth != null) {
            listmodel = new DefaultListModel<>();
            ListModel<Author> listauthor = this.listAuthor.getModel();
            for (int i = 0; i < listauthor.getSize(); i++) {
                if (auth != listauthor.getElementAt(i)) {
                    listmodel.addElement(listauthor.getElementAt(i));
                }
            }
            this.listAuthor.setModel(listmodel);
        }
        else
            JOptionPane.showMessageDialog(null, "Select Author First", "Invalid Selection", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRemoveAuthorActionPerformed

    private void tableBookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBookListMouseClicked
        // TODO add your handling code here:
        System.out.println("Author is adding");
        int tablerow = this.tableBookList.getSelectedRow();
        System.out.println("table row = "+tablerow);
        if (tablerow >0) {
            
            Book book = CommonDataStore.book.get(tablerow);
            //DefaultListModel listmodel = new DefaultListModel();
            DefaultListModel<Author> listmodel = new DefaultListModel<>();
            for (Author auth : book.getAuthor()) {
                listmodel.addElement(auth);
            }
            this.listShowAuthor.setModel(listmodel);
        }
    }//GEN-LAST:event_tableBookListMouseClicked

    private void comboAuthorMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_comboAuthorMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAuthorMouseWheelMoved

    private void comboAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboAuthorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAuthorMouseClicked

    private void comboAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAuthorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAuthor;
    private javax.swing.JButton btnRemoveAuthor;
    private javax.swing.JButton btnSaveBook;
    private javax.swing.JComboBox comboAuthor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listAuthor;
    private javax.swing.JList listShowAuthor;
    private javax.swing.JTable tableBookList;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
