/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ramesh.panels;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ramesh.data.CommonDataStore;
import ramesh.librarySystem.Book;
import ramesh.librarySystem.Copy;

/**
 *
 * @author Rkaran
 */
public class AddBookCopy extends javax.swing.JPanel {

    /**
     * Creates new form AddBookCopy
     */
    public AddBookCopy() {
        initComponents();
        updateList();
    }
    private void updateList(){
        DefaultTableModel tablemodel = (DefaultTableModel)this.tableBookList.getModel();
        for(Book book : CommonDataStore.book){
            tablemodel.addRow(book.getVectorBook());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBookList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCopyNo = new javax.swing.JTextField();
        buttonAddCopy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCopy = new javax.swing.JList();

        tableBookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "ISBN", "Available Copies", "Lend Copies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBookListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBookList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Click on book Name to add a copy");

        jLabel2.setText("Copy No");

        buttonAddCopy.setText("Add Copy");
        buttonAddCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddCopyActionPerformed(evt);
            }
        });

        listCopy.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Copies"));
        jScrollPane2.setViewportView(listCopy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCopyNo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(buttonAddCopy)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addComponent(jLabel1))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCopyNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddCopy))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddCopyActionPerformed
        int selectedrow = this.tableBookList.getSelectedRow();
        if(selectedrow >= 0 ){
            try{
                int copynum = Integer.parseInt(this.txtCopyNo.getText());
                for(int i =0;i<copynum;i++)
                    new Copy(CommonDataStore.book.get(selectedrow).getPublication());
                this.tableBookList.getModel().setValueAt(CommonDataStore.book.get(selectedrow).getNumberOfAvailableCopies(), selectedrow, 2);
                updateCopyList();
                
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Number of copies is not valid number", "Invalid Integer", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Select Book First", "Incomplete Data", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_buttonAddCopyActionPerformed

    private void tableBookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBookListMouseClicked

        updateCopyList();
    }//GEN-LAST:event_tableBookListMouseClicked

    private void updateCopyList(){
        int row = this.tableBookList.getSelectedRow() ;
        if(row>= 0){
            Book book = CommonDataStore.book.get(row);
            DefaultListModel<Copy> listmodel = new DefaultListModel<>();
            for(Copy copy : book.getCopy() ){
                listmodel.addElement(copy);
            }
            this.listCopy.setModel(listmodel);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddCopy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listCopy;
    private javax.swing.JTable tableBookList;
    private javax.swing.JTextField txtCopyNo;
    // End of variables declaration//GEN-END:variables
}
