/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ramesh.panels;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ramesh.data.CommonDataStore;
import ramesh.librarySystem.Copy;
import ramesh.librarySystem.Magazine;

/**
 *
 * @author Rkaran
 */
public class AddMagazineCopy extends javax.swing.JPanel {

    /**
     * Creates new form AddMagazineCopy
     */
    public AddMagazineCopy() {
        initComponents();
        updateMagazineTable();
    }
    private void updateMagazineTable(){
        DefaultTableModel tablelist = (DefaultTableModel)this.tableBookList.getModel();
        for(Magazine magazine: CommonDataStore.magazine)
            tablelist.addRow(magazine.getVector());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAddCopy = new javax.swing.JButton();
        txtCopyNo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCopy = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBookList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        buttonAddCopy.setText("Add Copy");
        buttonAddCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddCopyActionPerformed(evt);
            }
        });

        listCopy.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Copies"));
        jScrollPane2.setViewportView(listCopy);

        tableBookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Issue Number", "Available Copies", "Lend Copies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBookListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBookList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Click on Magazine Name to add a copy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(txtCopyNo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAddCopy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(jLabel1)))
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonAddCopy)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCopyNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(219, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddCopyActionPerformed
        int selectedrow = this.tableBookList.getSelectedRow();
        if(selectedrow >= 0 ){
            try{
                int copynum = Integer.parseInt(this.txtCopyNo.getText());
                for(int i =0;i<copynum;i++)
                    new Copy(CommonDataStore.magazine.get(selectedrow).getPublication());
                this.tableBookList.getModel().setValueAt(CommonDataStore.magazine.get(selectedrow).getNumberOfAvailableCopies(), selectedrow, 2);
                updateCopyList();

            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Number of copies is not valid number", "Invalid Integer", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Select Book First", "Incomplete Data", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_buttonAddCopyActionPerformed

    private void updateCopyList(){
        int row = this.tableBookList.getSelectedRow();
        if(row>=0)
        {
            DefaultListModel<Copy> listmodel = new DefaultListModel();
            for(Copy copy: CommonDataStore.magazine.get(row).getCopy())
                listmodel.addElement(copy);
            this.listCopy.setModel(listmodel);
        }
        
    }
    private void tableBookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBookListMouseClicked

        updateCopyList();
    }//GEN-LAST:event_tableBookListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddCopy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listCopy;
    private javax.swing.JTable tableBookList;
    private javax.swing.JTextField txtCopyNo;
    // End of variables declaration//GEN-END:variables
}
