/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ramesh.panels;

/**
 *
 * @author Rkaran
 */
public class AddPublicationCopy extends javax.swing.JPanel {

    /**
     * Creates new form AddPublicationCopy
     */
    public AddPublicationCopy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        addBookCopy1 = new ramesh.panels.AddBookCopy();
        addMagazineCopy1 = new ramesh.panels.AddMagazineCopy();
        addMagazineCopy2 = new ramesh.panels.AddMagazineCopy();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.addTab("Add Book Copy", addBookCopy1);

        javax.swing.GroupLayout addMagazineCopy1Layout = new javax.swing.GroupLayout(addMagazineCopy1);
        addMagazineCopy1.setLayout(addMagazineCopy1Layout);
        addMagazineCopy1Layout.setHorizontalGroup(
            addMagazineCopy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMagazineCopy1Layout.createSequentialGroup()
                .addComponent(addMagazineCopy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addMagazineCopy1Layout.setVerticalGroup(
            addMagazineCopy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMagazineCopy1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addMagazineCopy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Magazine Copy", addMagazineCopy1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ramesh.panels.AddBookCopy addBookCopy1;
    private ramesh.panels.AddMagazineCopy addMagazineCopy1;
    private ramesh.panels.AddMagazineCopy addMagazineCopy2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
