/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ramesh.panels;

/**
 *
 * @author Rkaran
 */
public class AddPublication extends javax.swing.JPanel {

    /**
     * Creates new form AddPublication
     */
    public AddPublication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBook1 = new ramesh.panels.AddBook();
        tabbedAddPublications = new javax.swing.JTabbedPane();
        addBook2 = new ramesh.panels.AddBook();
        addMagazine1 = new ramesh.panels.AddMagazine();

        setPreferredSize(new java.awt.Dimension(600, 520));

        tabbedAddPublications.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabbedAddPublications.addTab("Add Book", addBook2);
        tabbedAddPublications.addTab("Add Magazine", addMagazine1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedAddPublications, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedAddPublications, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ramesh.panels.AddBook addBook1;
    private ramesh.panels.AddBook addBook2;
    private ramesh.panels.AddMagazine addMagazine1;
    private javax.swing.JTabbedPane tabbedAddPublications;
    // End of variables declaration//GEN-END:variables
}
