/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ramesh.panels;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.JPanel;
import ramesh.data.CommonDataStore;
import ramesh.librarySystem.*;

/**
 *
 * @author Rkaran
 */
public class LibrarySystemUI extends javax.swing.JFrame {

    /**
     * Creates new form LibrarySystemUI
     */
    public LibrarySystemUI() {
        initComponents();
        for(int i =1;i<=10;i++){
            Address address = new Address("street"+i,"city"+i , "state"+i, "zip"+i);
            Person person = new Person("Author"+i, "Lname"+i, "phone"+i, address);
            Author author = new Author("Credential"+i, "Bio"+i, person);
            Book book = new Book("Book"+i, "ISBN"+i);
            book.addAuthor(author);
            
            Person person1 = new Person("Member"+i, "Lname"+i, "phone"+i, address);
            Member member = new Member(person1);
            CommonDataStore.member.add(member);
            Magazine magazine = new Magazine("Magazine"+i, i);
            CommonDataStore.book.add(book);
            CommonDataStore.author.add(author);
            CommonDataStore.magazine.add(magazine);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegister = new javax.swing.JMenu();
        btnRegisterMember = new javax.swing.JMenuItem();
        btnRegisterAuthor = new javax.swing.JMenuItem();
        menuAddPublication = new javax.swing.JMenu();
        menuAddPublicationCopy = new javax.swing.JMenu();
        menuLoan = new javax.swing.JMenu();
        menuDisplay = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuRegister.setText("Register");
        menuRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegisterMouseClicked(evt);
            }
        });

        btnRegisterMember.setText("Member");
        btnRegisterMember.setName("buttonRegisterMember"); // NOI18N
        btnRegisterMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterMemberActionPerformed(evt);
            }
        });
        menuRegister.add(btnRegisterMember);

        btnRegisterAuthor.setText("Author");
        btnRegisterAuthor.setName("buttonRegisterAuthor"); // NOI18N
        btnRegisterAuthor.setPreferredSize(new java.awt.Dimension(82, 22));
        btnRegisterAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterAuthorActionPerformed(evt);
            }
        });
        menuRegister.add(btnRegisterAuthor);

        jMenuBar1.add(menuRegister);

        menuAddPublication.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuAddPublication.setText("Add Publication");
        menuAddPublication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAddPublicationMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAddPublication);

        menuAddPublicationCopy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuAddPublicationCopy.setText("Add Publication Copy");
        menuAddPublicationCopy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAddPublicationCopyMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAddPublicationCopy);

        menuLoan.setText("Loan Section");
        menuLoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLoanMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLoan);

        menuDisplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuDisplay.setText("Display");
        menuDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDisplayMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDisplay);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterMemberActionPerformed
        // TODO add your handling code here:
        this.updatePanel(this.getContentPane(), new RegisterMember());
        //this.setSize(new RegisterMember().getWidth(), new RegisterMember().getHeight());
    }//GEN-LAST:event_btnRegisterMemberActionPerformed

    private void btnRegisterAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterAuthorActionPerformed
        // TODO add your handling code here:
        this.updatePanel(this.getContentPane(), new RegisterAuthor());
    }//GEN-LAST:event_btnRegisterAuthorActionPerformed

    private void menuRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegisterMouseClicked
        // TODO add your handling code here:
        System.out.println("Menu title");
    }//GEN-LAST:event_menuRegisterMouseClicked

    private void menuAddPublicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAddPublicationMouseClicked
        this.updatePanel(this.getContentPane(), new AddPublication());
    }//GEN-LAST:event_menuAddPublicationMouseClicked

    private void menuAddPublicationCopyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAddPublicationCopyMouseClicked
        
        this.updatePanel(this.getContentPane(), new AddPublicationCopy());
    }//GEN-LAST:event_menuAddPublicationCopyMouseClicked

    private void menuDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDisplayMouseClicked
        // TODO add your handling code here:
        this.updatePanel(this.getContentPane(), new Dispay());
    }//GEN-LAST:event_menuDisplayMouseClicked

    private void menuLoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLoanMouseClicked
        // TODO add your handling code here:
        this.updatePanel(this.getContentPane(), new LoanOperations());
    }//GEN-LAST:event_menuLoanMouseClicked

    public void updatePanel(Container container, JPanel panel){
        
        System.out.println("Updating console");
        container.removeAll();
        container.setLayout(new BorderLayout());
        container.add(panel);
        container.repaint();
        container.revalidate();
        
    }
    
    
    // User Defined Codes......
//    public static void showPanel(JPanel panel, LibrarySystemUI frame) {
//        JPanel homePanel = frame.getHomePanel();
//        panel.setVisible(true);
//        homePanel.remove(frame.getHomeBGLabel());
//        homePanel.setLayout(new BorderLayout());
//        homePanel.add(panel);
//        homePanel.repaint();
//        homePanel.revalidate();
//        System.out.print("Panel is added");
//    }
//
//    public static void showHomePanel(LibrarySystemUI frame) {
//        JPanel homePanel = frame.getHomePanel();
//        homePanel.removeAll();
//        homePanel.setLayout(new BorderLayout());
//        homePanel.add(frame.getHomeBGLabel());
//        homePanel.repaint();
//        homePanel.revalidate();
//        System.out.print("Panel is swapped back");
//        
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarySystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarySystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarySystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarySystemUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarySystemUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnRegisterAuthor;
    private javax.swing.JMenuItem btnRegisterMember;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuAddPublication;
    private javax.swing.JMenu menuAddPublicationCopy;
    private javax.swing.JMenu menuDisplay;
    private javax.swing.JMenu menuLoan;
    private javax.swing.JMenu menuRegister;
    // End of variables declaration//GEN-END:variables
}
