/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ramesh.panels;

import java.util.Date;
import javax.swing.table.DefaultTableModel;
import ramesh.data.CommonDataStore;
import ramesh.librarySystem.*;

/**
 *
 * @author Rkaran
 */
public class LoanPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanPanel
     */
    public LoanPanel() {
        initComponents();
        loadUserList();
    }

    private void loadUserList() {
        for (Member member : CommonDataStore.member) {
            this.comboBoxUser.addItem(member);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        comboBoxUser = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        radioButtonMagazine = new javax.swing.JRadioButton();
        radioButtonBook = new javax.swing.JRadioButton();
        comboBoxPublication = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAvailableItesm = new javax.swing.JTextField();
        buttonLoan = new javax.swing.JButton();
        buttonReserve = new javax.swing.JButton();
        buttonReturn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUserLoan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReservation = new javax.swing.JTable();

        jLabel1.setText("Select User ID");

        comboBoxUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxUserActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Publication"));

        radioGroup.add(radioButtonMagazine);
        radioButtonMagazine.setText("Magazine");
        radioButtonMagazine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonMagazineActionPerformed(evt);
            }
        });

        radioGroup.add(radioButtonBook);
        radioButtonBook.setText("Books");
        radioButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonBookActionPerformed(evt);
            }
        });

        comboBoxPublication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBoxPublicationMouseClicked(evt);
            }
        });
        comboBoxPublication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPublicationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtonMagazine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButtonBook)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(comboBoxPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonMagazine)
                    .addComponent(radioButtonBook))
                .addGap(18, 18, 18)
                .addComponent(comboBoxPublication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setText("Available Items");

        txtAvailableItesm.setEnabled(false);

        buttonLoan.setText("Loan");
        buttonLoan.setEnabled(false);
        buttonLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoanActionPerformed(evt);
            }
        });

        buttonReserve.setText("Reserve");
        buttonReserve.setEnabled(false);
        buttonReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReserveActionPerformed(evt);
            }
        });

        buttonReturn.setText("Return");
        buttonReturn.setEnabled(false);
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonReserve)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtAvailableItesm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonReturn)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLoan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAvailableItesm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLoan)
                    .addComponent(buttonReserve)
                    .addComponent(buttonReturn))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tableUserLoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Copy Num", "Title", "Issue Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableUserLoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserLoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUserLoan);

        tableReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation Date", "Publication Title", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableReservation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonMagazineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonMagazineActionPerformed
        // TODO add your handling code here:
        this.comboBoxPublication.removeAllItems();
        for (Magazine magazine : CommonDataStore.magazine) {
            this.comboBoxPublication.addItem(magazine);
        }
    }//GEN-LAST:event_radioButtonMagazineActionPerformed

    private void radioButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonBookActionPerformed
        this.comboBoxPublication.removeAllItems();
        for (Book book : CommonDataStore.book) {
            this.comboBoxPublication.addItem(book);
        }
    }//GEN-LAST:event_radioButtonBookActionPerformed

    private void buttonLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoanActionPerformed
        // TODO add your handling code here:

        Member member = (Member) this.comboBoxUser.getSelectedItem();
        if (this.radioButtonBook.isSelected()) {
            Book book = (Book) this.comboBoxPublication.getSelectedItem();
            //Loan loan = new Loan(new Date(), null, member, book.loanCopy());
            //book.loanCopy(member);
            member.Loan(book.loanCopy());
            
            updateGUI(book.getNumberOfAvailableCopies());
        } else if (this.radioButtonMagazine.isSelected()) {
            Magazine magazine = (Magazine) this.comboBoxPublication.getSelectedItem();
            //Loan loan = new Loan(new Date(), null, member, magazine.loanCopy());
            //magazine.loanCopy(member);
            member.Loan(magazine.loanCopy());
            updateGUI(magazine.getNumberOfAvailableCopies());
        }
        System.out.println("Book loaned");
        updateTable();

    }//GEN-LAST:event_buttonLoanActionPerformed

    private void comboBoxPublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPublicationActionPerformed
        // TODO add your handling code here:
        int availableCopy = 0;
        if (this.comboBoxPublication.getItemCount() > 0) {
            if (this.radioButtonBook.isSelected()) {
                Book book = (Book) this.comboBoxPublication.getSelectedItem();
                availableCopy = book.getNumberOfAvailableCopies();
                this.txtAvailableItesm.setText(Integer.toString(availableCopy));
            } else if (this.radioButtonMagazine.isSelected()) {
                Magazine magazine = (Magazine) this.comboBoxPublication.getSelectedItem();
                availableCopy = magazine.getNumberOfAvailableCopies();
                this.txtAvailableItesm.setText(Integer.toString(availableCopy));
            }
            updateGUI(availableCopy);
        }
    }//GEN-LAST:event_comboBoxPublicationActionPerformed

    private void comboBoxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxUserActionPerformed
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_comboBoxUserActionPerformed

    private void comboBoxPublicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxPublicationMouseClicked
        // TODO add your handling code here:
        int availableCopy = 0;
        if (this.radioButtonBook.isSelected()) {
            Book book = (Book) this.comboBoxPublication.getSelectedItem();
            availableCopy = book.getNumberOfAvailableCopies();
            this.txtAvailableItesm.setText(Integer.toString(availableCopy));
        } else if (this.radioButtonMagazine.isSelected()) {
            Magazine magazine = (Magazine) this.comboBoxPublication.getSelectedItem();
            availableCopy = magazine.getNumberOfAvailableCopies();
            this.txtAvailableItesm.setText(Integer.toString(availableCopy));
        }
        updateGUI(availableCopy);
    }//GEN-LAST:event_comboBoxPublicationMouseClicked

    private void tableUserLoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserLoanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableUserLoanMouseClicked

    private void buttonReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReserveActionPerformed
        // TODO add your handling code here:
        
        if(this.radioButtonBook.isSelected() ){
            Book book = (Book)this.comboBoxPublication.getSelectedItem();
            Member member = (Member)this.comboBoxUser.getSelectedItem();
            member.Reserve(book);
            System.out.println("Book Reserved");
        }
        else if(this.radioButtonMagazine.isSelected()){
            Magazine magazine = (Magazine)this.comboBoxPublication.getSelectedItem();
            Member member = (Member)this.comboBoxUser.getSelectedItem();
            member.Reserve(magazine);
            System.out.println("Magazine Reserved");
        }
        updateTable();
    }//GEN-LAST:event_buttonReserveActionPerformed

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void updateTable() {
        Member member = (Member) this.comboBoxUser.getSelectedItem();
        
        // For Loan Table
        DefaultTableModel tablemodel = (DefaultTableModel) this.tableUserLoan.getModel();
        int row = tablemodel.getRowCount();
        for (int i = 0; i < row; i++) {
            tablemodel.removeRow(0);
        }
        for (Loan loan : member.getLoans()) {
            tablemodel.addRow(loan.getVector());
        }
        
        // For Reservation Table
        tablemodel = (DefaultTableModel) this.tableReservation.getModel();
        row = tablemodel.getRowCount();
        for (int i = 0; i < row; i++) {
            tablemodel.removeRow(0);
        }
        for(Reservation reservation : member.getReservation()){
            tablemodel.addRow(reservation.getVector());
        }
        
        
        System.out.println("Loan Added to Table");
    }

    private void updateGUI(int availablecopy) {
        if (availablecopy > 0) {
            {
                this.buttonLoan.setEnabled(true);
                this.buttonReserve.setEnabled(false);
            }
        } else {
            this.buttonReserve.setEnabled(true);
            this.buttonLoan.setEnabled(false);
        }
        this.txtAvailableItesm.setText(Integer.toString(availablecopy));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLoan;
    private javax.swing.JButton buttonReserve;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JComboBox comboBoxPublication;
    private javax.swing.JComboBox comboBoxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioButtonBook;
    private javax.swing.JRadioButton radioButtonMagazine;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JTable tableReservation;
    private javax.swing.JTable tableUserLoan;
    private javax.swing.JTextField txtAvailableItesm;
    // End of variables declaration//GEN-END:variables
}
