/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ramesh.panels;

/**
 *
 * @author Ramesh
 */
public class LoanOperations extends javax.swing.JPanel {

    /**
     * Creates new form LoanOperations
     */
    public LoanOperations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        loanPanel1 = new ramesh.panels.LoanPanel();
        returnLoan1 = new ramesh.panels.ReturnLoan();
        pickUpReservation1 = new ramesh.panels.PickUpReservation();
        pickUpReservation2 = new ramesh.panels.PickUpReservation();

        jTabbedPane1.addTab("Laon and Reserve", loanPanel1);
        jTabbedPane1.addTab("Return Loan", returnLoan1);

        javax.swing.GroupLayout pickUpReservation1Layout = new javax.swing.GroupLayout(pickUpReservation1);
        pickUpReservation1.setLayout(pickUpReservation1Layout);
        pickUpReservation1Layout.setHorizontalGroup(
            pickUpReservation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pickUpReservation1Layout.createSequentialGroup()
                .addComponent(pickUpReservation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 311, Short.MAX_VALUE))
        );
        pickUpReservation1Layout.setVerticalGroup(
            pickUpReservation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pickUpReservation1Layout.createSequentialGroup()
                .addComponent(pickUpReservation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pick Up Reservation", pickUpReservation1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private ramesh.panels.LoanPanel loanPanel1;
    private ramesh.panels.PickUpReservation pickUpReservation1;
    private ramesh.panels.PickUpReservation pickUpReservation2;
    private ramesh.panels.ReturnLoan returnLoan1;
    // End of variables declaration//GEN-END:variables
}
