/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ramesh.panels;

import javax.swing.table.DefaultTableModel;
import ramesh.data.CommonDataStore;
import ramesh.librarySystem.Loan;
import ramesh.librarySystem.Member;
import ramesh.librarySystem.Reservation;

/**
 *
 * @author Ramesh
 */
public class PickUpReservation extends javax.swing.JPanel {
    
    Member selectedMember ;
    /**
     * Creates new form PickUpReservation
     */
    public PickUpReservation() {
        initComponents();
        loadMember();
    }
    
    private void loadMember() {
        for (ramesh.librarySystem.Member member : CommonDataStore.member) {
            this.comboMember.addItem(member);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboMember = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservation = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Member Name");

        comboMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMemberActionPerformed(evt);
            }
        });

        tableReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IssueDate", "Title", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableReservation);

        jButton1.setText("Pick Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel Reservation");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(comboMember, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1)
                        .addGap(67, 67, 67)
                        .addComponent(jButton2)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMemberActionPerformed
        // TODO add your handling code here:
        this.selectedMember = (Member)this.comboMember.getSelectedItem();
        if ( this.selectedMember !=null) 
        {
            DefaultTableModel tablemodel = (DefaultTableModel) this.tableReservation.getModel();
            int row = tablemodel.getRowCount();
            for(int i =0;i<row;i++)
                tablemodel.removeRow(0);
            for(Reservation reservation: selectedMember.getReservation())
                tablemodel.addRow(reservation.getVector());
        }
    }//GEN-LAST:event_comboMemberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedrow = this.tableReservation.getSelectedRowCount();
        if(selectedrow>=0)
        {
//            Reservation reservation = this.selectedMember.getReservation().get(selectedrow-1);
            Reservation reservation = this.selectedMember.getReservation().get(selectedrow-1);
            selectedMember.pickUpReservation(reservation);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedrow = this.tableReservation.getSelectedRowCount();
        if(selectedrow>=0)
        {
            Reservation reservation = this.selectedMember.getReservation().get(selectedrow-1);
            selectedMember.cancelReservation(reservation);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboMember;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReservation;
    // End of variables declaration//GEN-END:variables
}
