/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ramesh.panels;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ramesh.data.CommonDataStore;
import ramesh.librarySystem.Copy;
import ramesh.librarySystem.Loan;
import ramesh.librarySystem.Member;

/**
 *
 * @author Ramesh
 */
public class ReturnLoan extends javax.swing.JPanel {

    Member selectedMember = null;
    
    /**
     * Creates new form ReturnLoan
     */
    public ReturnLoan() {
        initComponents();
        loadMember();
    }

    private void loadMember() {
        for (Member member : CommonDataStore.member) {
            this.comboMember.addItem(member);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboMember = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLoanList = new javax.swing.JTable();
        buttonReturn = new javax.swing.JButton();

        jLabel1.setText("Member Name");

        comboMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMemberActionPerformed(evt);
            }
        });

        tableLoanList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "issue Date", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableLoanList);

        buttonReturn.setText("Return Selected");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboMember, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(buttonReturn)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonReturn)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMemberActionPerformed
        // TODO add your handling code here:
        selectedMember = (Member)this.comboMember.getSelectedItem();
        if ( this.selectedMember !=null) 
        {
            DefaultTableModel tablemodel = (DefaultTableModel) this.tableLoanList.getModel();
            int row = tablemodel.getRowCount();
            for(int i =0;i<row;i++)
                tablemodel.removeRow(0);
            for(Loan loan: selectedMember.getLoans())
                tablemodel.addRow(loan.getVector());
        }

    }//GEN-LAST:event_comboMemberActionPerformed

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        // TODO add your handling code here:
        int selectedrow = this.tableLoanList.getSelectedRow();
        if(selectedrow >=0){
            Copy copy = this.selectedMember.getLoans().get(selectedrow).getCopy();
            if(copy.getLoan().getReturnDate() ==null )
                this.selectedMember.returnlt(copy);
            else
                JOptionPane.showMessageDialog(null, "This is already returned", "Old Loan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonReturnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonReturn;
    private javax.swing.JComboBox comboMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLoanList;
    // End of variables declaration//GEN-END:variables
}
